server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shoppingCart
    username: shoppingCart
    password: shoppingCart

logging:
  level:
    ru.yandex.practicum.client.ProductClient: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

feign:
  client:
    config:
      warehouse:
        loggerLevel: full