server:
  port: 0

spring:
  application:
    name: shopping-store
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
    discovery:
      enabled: true
      serviceId: config-server
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    ru.yandex.practicum.client.ProductClient: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

feign:
  client:
    config:
      warehouse:
        loggerLevel: full