spring:
  application:
    name: shopping-cart
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
    discovery:
      enabled: true
      serviceId: config-server
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/