CREATE TABLE IF NOT EXISTS carts (
    id UUID GENERATED PRIMARY KEY,
    username VARCHAR(255),
    state VARCHAR(255)
)

CREATE TABLE IF NOT EXISTS orders (
    id UUID GENERATED ALWAYS PRIMARY KEY,
    cart_id UUID,
    name VARCHAR(255),
    count_products INTEGER
)